services:
  - type: web
    name: gwbot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
